---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-petclinic
  namespace: petclinic-staging
  labels:
    app: spring-petclinic
    lifecycle: staging
    version: __VERSION__
spec:
  selector:
    matchLabels:
      app: spring-petclinic
      lifecycle: staging
  template:
    metadata:
      labels:
        app: spring-petclinic
        lifecycle: staging
    spec:
      containers:
      - name: spring-petclinic
        image: whummelink/spring-petclinic:__VERSION__
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
      #volumes:
      #volumes:
  progressDeadlineSeconds: 600  
  revisionHistoryLimit: 2  
