---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-petclinic
  namespace: petclinic-staging
  labels:
    app: spring-petclinic
    lifecycle: staging
    version: __VERSION__
spec:
 
  selector:
    matchLabels:
      app: spring-petclinic
      lifecycle: staging
      version: __VERSION__
  template:
    spec:
      metadata:
        labels:
          app: spring-petclinic
          lifecycle: staging
          version: __VERSION__
      containers:
      - name: spring-petclinic
        image: whummelink/spring-petclinic:__VERSION__
        ports:
          - name: http
            protocol: TCP
            containerPort: 8080
      #volumes:
  
